# Generated by Django 5.1.5 on 2025-01-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.CharField(max_length=50)),
                ('money_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_names', models.TextField()),
            ],
            options={
                'db_table': 'Budget',
            },
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amasaha', models.CharField(max_length=255)),
                ('money', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('impavu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'income',
            },
        ),
        migrations.CreateModel(
            name='outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amasaha', models.CharField(max_length=255)),
                ('money', models.CharField(max_length=255)),
                ('impavu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'outcome',
            },
        ),
    ]
