# Generated by Django 5.1.5 on 2025-01-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='account',
            field=models.CharField(default='yed', max_length=255),
            preserve_default=False,
        ),
    ]
