# Generated by Django 5.1.5 on 2025-01-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_number',
            field=models.TextField(),
        ),
    ]
