# Generated by Django 5.1.5 on 2025-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_alter_accounts_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_number',
            field=models.CharField(max_length=255),
        ),
    ]
