# Generated by Django 5.1.5 on 2025-01-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0005_alter_accounts_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='account_number',
        ),
    ]
